name: Api
on:
  push:
    branches:
      - main
jobs:
  russia:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        params:
          - central-fed-district-latest.osm.pbf/central-fed-district
          - crimean-fed-district-latest.osm.pbf/crimean-fed-district
          - far-eastern-fed-district-latest.osm.pbf/far-eastern-fed-district
          - north-caucasus-fed-district-latest.osm.pbf/north-caucasus-fed-district
          - northwestern-fed-district-latest.osm.pbf/northwestern-fed-district
          - siberian-fed-district-latest.osm.pbf/siberian-fed-district
          - south-fed-district-latest.osm.pbf/south-fed-district
          - ural-fed-district-latest.osm.pbf/ural-fed-district
          - volga-fed-district-latest.osm.pbf/volga-fed-district
          - kaliningrad-latest.osm.pbf/kaliningrad
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Get env from matrix
        run: |
          MATRIX=${{matrix.params}}
          MATRIX_FILE=${MATRIX%/*}
          MATRIX_TAG=${MATRIX#*/}
          echo "MATRIX_FILE=$MATRIX_FILE" >> $GITHUB_ENV
          echo "MATRIX_TAG=$MATRIX_TAG" >> $GITHUB_ENV
      - name: Make dir
        run: mkdir -p custom_files
      - name: Dowload data file
        run: wget https://download.geofabrik.de/${{ github.job }}/$MATRIX_FILE -O custom_files/$MATRIX_FILE
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          build-args: OSM_FILE=${{ env.MATRIX_FILE }}
          tags: ghcr.io/deemakuzovkin/valhalla-docker:${{ env.MATRIX_TAG }}
  africa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        params:
          - algeria-latest.osm.pbf/algeria
          - angola-latest.osm.pbf/angola
          - benin-latest.osm.pbf/benin
          - botswana-latest.osm.pbf/botswana
          - burkina-faso-latest.osm.pbf/burkina-faso
          - burundi-latest.osm.pbf/burundi
          - cameroon-latest.osm.pbf/cameroon
          - canary-islands-latest.osm.pbf/canary-islands
          - cape-verde-latest.osm.pbf/cape-verde
          - central-african-republic-latest.osm.pbf/central-african-republic
          - chad-latest.osm.pbf/chad
          - comores-latest.osm.pbf/comores
          - congo-brazzaville-latest.osm.pbf/congo-brazzaville
          - congo-democratic-republic-latest.osm.pbf/congo-democratic-republic
          - djibouti-latest.osm.pbf/djibouti
          - egypt-latest.osm.pbf/egypt
          - equatorial-guinea-latest.osm.pbf/equatorial-guinea
          - eritrea-latest.osm.pbf/eritrea
          - ethiopia-latest.osm.pbf/ethiopia
          - gabon-latest.osm.pbf/gabon
          - ghana-latest.osm.pbf/ghana
          - guinea-latest.osm.pbf/guinea
          - guinea-bissau-latest.osm.pbf/guinea-bissau
          - ivory-coast-latest.osm.pbf/ivory-coast
          - kenya-latest.osm.pbf/kenya
          - lesotho-latest.osm.pbf/lesotho
          - liberia-latest.osm.pbf/liberia
          - libya-latest.osm.pbf/libya
          - madagascar-latest.osm.pbf/madagascar
          - malawi-latest.osm.pbf/malawi
          - mali-latest.osm.pbf/mali
          - mauritania-latest.osm.pbf/mauritania
          - mauritius-latest.osm.pbf/mauritius
          - morocco-latest.osm.pbf/morocco
          - mozambique-latest.osm.pbf/mozambique
          - namibia-latest.osm.pbf/namibia
          - niger-latest.osm.pbf/niger
          - nigeria-latest.osm.pbf/nigeria
          - rwanda-latest.osm.pbf/rwanda
          - saint-helena-ascension-and-tristan-da-cunha-latest.osm.pbf/saint-helena-ascension-and-tristan-da-cunha
          - sao-tome-and-principe-latest.osm.pbf/sao-tome-and-principe
          - senegal-and-gambia-latest.osm.pbf/senegal-and-gambia
          - seychelles-latest.osm.pbf/seychelles
          - sierra-leone-latest.osm.pbf/sierra-leone
          - somalia-latest.osm.pbf/somalia
          - south-africa-latest.osm.pbf/south-africa
          - south-sudan-latest.osm.pbf/south-sudan
          - sudan-latest.osm.pbf/sudan
          - swaziland-latest.osm.pbf/swaziland
          - tanzania-latest.osm.pbf/tanzania
          - togo-latest.osm.pbf/togo
          - tunisia-latest.osm.pbf/tunisia
          - uganda-latest.osm.pbf/uganda
          - zambia-latest.osm.pbf/zambia
          - zimbabwe-latest.osm.pbf/zimbabwe
          - south-africa-and-lesotho-latest.osm.pbf/south-africa-and-lesotho
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Get env from matrix
        run: |
          MATRIX=${{matrix.params}}
          MATRIX_FILE=${MATRIX%/*}
          MATRIX_TAG=${MATRIX#*/}
          echo "MATRIX_FILE=$MATRIX_FILE" >> $GITHUB_ENV
          echo "MATRIX_TAG=$MATRIX_TAG" >> $GITHUB_ENV
      - name: Make dir
        run: mkdir -p custom_files
      - name: Dowload data file
        run: wget https://download.geofabrik.de/${{ github.job }}/$MATRIX_FILE -O custom_files/$MATRIX_FILE
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          build-args: OSM_FILE=${{ env.MATRIX_FILE }}
          tags: ghcr.io/deemakuzovkin/valhalla-docker:${{ env.MATRIX_TAG }}
